idf_component_register(
    SRCS
        "app_main.c"
        "wifi_station.c"
        "robot_state.c"
        "telemetry_http.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        board_hw
        esp_system
        esp_timer
        esp_wifi
        esp_event
        esp_netif
        nvs_flash
        freertos
        driver
        motor
        servo
        frame_sensor
        hc_sr04
        relay
        esp_http_server
)
